version: '3.8'

services:
  docker-mysql:
    container_name: docker-mysql
    image: mysql
    restart: always
    environment:
        MYSQL_DATABASE : ecomm
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER : root
        MYSQL_ROOT_HOST : '%'
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "5555:3306" 

  product-service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/ecomm
    depends_on:
      - docker-mysql
    volumes:
      - app-data:/app

#Define named volumes for persistent data
volumes:
  app-data:
  db-data:  

    
      



